project: poost

templates:
  common:
    properties:
      CXX_STANDARD: 20
      CXX_STANDARD_REQUIRED: ON
    compile_options:
      global:
        - -Wall
        - -Wextra
        - -Wpedantic
      configurations:
        Release:
          - -Werror

  asan:
    compile_options:
      configurations:
        Asan:
          - ${CMAKE_CXX_FLAGS_DEBUG}
          - -O1
          - -fno-omit-frame-pointer
          - -fno-optimize-sibling-calls
          - -fsanitize=address
    link_options:
      configurations:
        Asan:
          - ${CMAKE_EXE_LINKER_FLAGS_DEBUG}
          - -g
          - -fsanitize=address

  ubsan:
    compile_options:
      configurations:
        Ubsan:
          - ${CMAKE_CXX_FLAGS_DEBUG}
          - -O1
          - -fno-omit-frame-pointer
          - -fno-optimize-sibling-calls
          - -fsanitize=undefined
          - -fno-sanitize-recover
    link_options:
      configurations:
        Ubsan:
          - ${CMAKE_EXE_LINKER_FLAGS_DEBUG}
          - -g
          - -fsanitize=undefined

packages:
  - external: external/doctest
    if: PROJECT_IS_TOP_LEVEL
    url: https://github.com/doctest/doctest
    options:
      DOCTEST_NO_INSTALL: ON

targets:
  - library: poost
    templates:
      - common
    aliases:
      - poost::poost
    sources:
      - include/poost/args.hpp
      - src/poost/args.cpp

      - include/poost/log.hpp
      - src/poost/log.cpp

      - include/poost/assert.hpp
    includes:
      public:
        - include
      private:
        - include/poost

  - executable: poost_test
    if: PROJECT_IS_TOP_LEVEL
    templates:
      - common
      - asan
      - ubsan
    sources:
      - tests/args_test.cpp
    includes:
      - src/poost
    dependencies:
      - doctest::doctest_with_main
      - poost::poost
